kafka:
  broker: "localhost:9092"
  consumer:
    group_id: "agent_group"
    auto_offset_reset: "latest"
  transcription_input_topic: "transcriptions.all"
  transcription_output_topic: "transcriptions.agent.action"
  intent_input_topic: "transcriptions.agent.action"

ollama:
  url: "http://localhost:11434"
  model: "llama3.2"
  system_prompt_file: "config/prompts.yml"

text_to_speech:
  api_url: "http://localhost:8000/v1/audio/speech"
  api_key: "sk-111111111"
  default_model: "tts-1"
  default_voice: "alloy"
  default_speed: 0.75
  response_format: "mp3"
