kafka:
  broker: "localhost:9092"
  schema_registry_url: "http://localhost:8081"
  consumer:
    group_id: "agent_group"
    auto_offset_reset: "latest"

  consumer_groups:
    real_time: "real_time_consumer_group"
    persistence: "persistence_consumer_group"
    session: "session_consumer_group"
    aggregator: "aggregator_consumer_group"
    transcription: "transcription_consumer_group"
    intent: "intent_consumer_group"

  transcriptions_topic: "transcriptions.all"
  actions_topic: "transcriptions.agent.action"
  sessions_management_topic: "sessions.management"
  aggregations_request_topic: "aggregations.request"

db:
  host: "localhost"
  port: 5432
  database: "transcriptsdb"
  user: "user"
  password: "password"

ollama:
  url: "http://localhost:11434"
  model: "llama3.2"
  system_prompt_file: "config/prompts.yml"

text_to_speech:
  api_url: "http://localhost:8000/v1/audio/speech"
  api_key: "sk-111111111"
  default_model: "tts-1"
  default_voice: "alloy"
  default_speed: 0.75
  response_format: "mp3"

app:
  voice_session_timeout_hours: 1